---
title: "Streamlining code"
subtitle: "Part 6"
title-block-banner: true
toc: true
---

::: {.center-text .large-fa-icon .teal-text}
{{< fa code title="symbol for code, </>" >}}
:::

## {{< fa box-open title="an open box" >}} Required Packages {#pkgs}

We'll be using the following R packages: 

```{r}
#| eval: false
#| echo: true
#| code-line-numbers: false
library(shiny)
library(shinyWidgets)
library(tidyverse)
```

## {{< fa table title="a data table" >}} Required Data {#data}

```{r}
#| eval: false
#| echo: true
#| code-line-numbers: false
library(palmerpenguins)
library(gapminder)
```

## {{< fa person-chalkboard title="A person motioning at a chalkboard" >}} Lecture Materials {#lecture-materials}

<!-- Part 6 is broken down into two lessons: -->

| {{< fa person-chalkboard title="A person motioning at a chalkboard" >}} Lecture slides   | 
|------------------------------------------------------------------------------------------|
| [Lecture 6.1: Functions](slides/part6.1-functions-slides.qmd){target="_blank"}  |
| [Lecture 6.2: Modules](slides/part6.2-modules-slides.qmd){target="_blank"}  |
: {.hover .bordered tbl-colwidths="[50,25,25]"}

<!-- ::: {.grid} -->

<!-- ::: {.g-col-12 .g-col-md-6} -->
<!-- ::: {.center-text} -->
<!-- [**Functions**]{.teal-text .body-text-m} -->

<!-- [{{< fa person-chalkboard title="A person motioning at a chalkboard" >}} lecture 6.1 slides](slides/part6.1-functions-slides.qmd){.btn role="button" target="_blank"}  -->
<!-- ::: -->
<!-- ::: -->

<!-- ::: {.g-col-12 .g-col-md-6} -->
<!-- ::: {.center-text} -->
<!-- [**Modules**]{.teal-text .body-text-m} -->

<!-- [{{< fa person-chalkboard title="A person motioning at a chalkboard" >}} lecture 6.2 slides](slides/part6.2-modules-slides.qmd){.btn role="button" target="_blank"}  -->
<!-- ::: -->
<!-- ::: -->

<!-- ::: -->
